sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.8
jdk:
  - openjdk8
env:
  - SCALAJS_VERSION=1.0.0-M8
script:
  - ./scripts/assemble-cli.sh $SCALAJS_VERSION $TRAVIS_SCALA_VERSION
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
